<?php
//
// ETS2MP Homepage language file.
// File:				czech.php
// Language name: 		Czech
// Translated name: 	Čeština
//

$_lang["download"] = "Stáhnout";
$_lang["home"] = "Domů";
$_lang["status"] = "Status";
$_lang["username"] = "Uživatelské jméno";
$_lang["password"] = "Heslo";
$_lang["login"] = "Přihlásit";
$_lang["register"] = "Registrace";
$_lang["download.latest.version"] = "Stáhnout nejnovější verzi";
$_lang["current.release"] = "Aktuální verze";
$_lang["language"] = "Jazyk";
$_lang["join"] = "PŘIDAT SE";
$_lang["mainpage.join"] = "Přidejte se k tisícům nadšenců do trucků on-line!";
$_lang["ts3.advertisement"] = "Hlasová komunikace s ostatními řidiči - klikněte zde pro připojení na TS3 server.";
$_lang["facebook.advertisement"] = "Nejnovější informace jsou na našem Facebooku.";
$_lang["registration.blocked"] = "Registrace zablokována - Pořád pracujeme na několika funkcích, kvůli kterým ještě nemůžeme zapnout registrace. Zapneme je, jakmile bude vše hotovo a budeme připraveni vydat novou verzi.";
$_lang["invalid.username.password"] = "Neplatné uživatelské jméno či heslo.";
$_lang["already.logged"] = "Již jste přihlášeni.";
$_lang["welcome"] = "Vítej,";
$_lang["logout"] = "Odhlásit se";
$_lang["bans"] = "Bany";
$_lang["version"] = "Verze";
$_lang["update.time"] = "Poslední update";
$_lang["req.game.version"] = "Vyžadovaná verze hry";
$_lang["requires"] = "Vyžaduje";
$_lang["or.newer"] = "nebo novější";
$_lang["game.client"] = "Herní klient";
$_lang["download.no.permissions"] = "Pro stažení modu musíte být přihlášeni";
$_lang["why.create.account"] = "Proč si založit účet?<br />Budete moci použít jediný účet pro přihlášení do všech služeb (fórum, hra, ekonomika a další). Plánujeme ho využít pro ekonomike a osobní statistiky řidičů. Váš profil si budete moci upravovat.";
$_lang["website.title"] = "ETS2MP - virtuální truckerský svět - multiplayer mod pro hru Euro Truck Simulator 2 od SCS Software";
$_lang["cookies.warning"] = "Tato stránka používá <a href=\"http://cs.wikipedia.org/wiki/HTTP_cookie\">cookies</a>. Dalším prohlížením této stránky s jejich použitím souhlasíte.";
$_lang["forum"] = "Fórum";
$_lang["cannot.create.account.when.logged"] = "Pokud jste již přihlášeni, nemůžete vytvořit nový účet.";
$_lang["successfully.registered"] = "Registrace proběhla úspěšně.";
$_lang["error.unknown"] = "Neznámá chyba";
$_lang["credentials.taken"] = "Uživatelské jméno, email nebo Steam ID jsou již obsazeny.";
$_lang["error.no.steam.data"] = "Pro vytvoření ETS2MP účtu musíte mít na vašem Steam účtu mít aktivovanou hru ETS2. Pokud ji ve své knihovně máte, přesvědčte se, že váš profil je veřejný. Pokud je soukromý, změnte ho na veřejný a klikněte na";
$_lang["register.steam.info"] = "Pro registraci se musíte přihlásit s vaším Steam účtem. Klikněte na tlačítko níže pro přesměrování na autentikační stránku Steamu.";
$_lang["rules.info"] = "Kliknutím na tlačítko Registrovat souhlasíte s našimi komunitními pravidly. Pro jejich přečtení klikněte zde.";
$_lang["E-Mail"] = "Email";
$_lang["repeat.mail"] = "Email znovu";
$_lang["new.password"] = "Nové heslo";
$_lang["repeat.new.password"] = "Nové heslo znovu";
$_lang["new.password.summary"] = "Pokud tyto pole nevyplníte, heslo zůstane stejné.";
$_lang["old.password"] = "Staré heslo";
$_lang["repeat.old.password"] = "Staré heslo znovu";
$_lang["save.account.data"] = "Uložit data účtu";
$_lang["edit.account"] = "Upravit účet";
$_lang["forgot.password"] = "Zapomněli jste heslo? Klikněte <a href=\"index.php?page=resetPassword\">zde</a>.";
$_lang["forgot.password.summary"] = "Zapomněli jste vaše heslo? Napište váš email do pole níže a klikněte na tlačítko \"Připomenout heslo\".";
$_lang["reminder.button"] = "Připomenout heslo";
$_lang["reset.password"] = "Resetování hesla";
$_lang["password.reminder.mail.title"] = "Žádost o připomenutí hesla.";
$_lang["password.reminder.content"] = "Dobrý den.\n\nNěkdo z IP {0} si vyžádal změnu hesla od vašeho ETS2MP účtu.\n\nPro resetování vašeho hesla klikněte na tento odkaz: {1}.\nPokud jste to nebyli vy, tento email můžete ignorovat.\n\nDěkujeme\nTým ETS2MP";
$_lang["new.password.mail.title"] = "Vaše nové heslo.";
$_lang["new.password.mail.content"] = "Dobrý den.\n\nVaše nové heslo je: {0}\n\nNezapomeňte si ho hned po přihlášení změnit.\n\nDěkujeme\nTým ETS2MP";
$_lang["account.activated"] = "Váš účet byl úspěšně aktivován.";
$_lang["unable.to.activate"] = "Nepodařilo se nám aktivovat váš účet, protože je neplatný nebo je účet již aktivován.";
$_lang["not.activated"] = "Váš účet ještě není aktivován. Pokud vám nepřšla aktivační zpráva, klikněte <a href=\"index.php?action=resendActivation\">zde</a> pro znovuodeslání.";
$_lang["force.password.change"] = "Změňte si prosím heslo. Můžete ho změnit <a href=\"index.php?page=editAccount\">zde</a>.";
$_lang["forgot.password.link.sent"] = "Zkontrolujte si email. Poslali jsme vám odkaz na resetování hesla.";
$_lang["forgot.password.sent"] = "Zkontrolujte si email. Poslali jsme vám vaše nové heslo.";
$_lang["forgot.password.invalid.key"] = "Klíč na resetování hesla je neplatný.";
$_lang["activation.key.resent"] = "Nový aktivační klíč byl odeslán na váš email.";
$_lang["activation.mail.title"] = "Aktivace ETS2MP účtu.";
$_lang["activation.mail.content"] = "Dobrý den\n\nToto je váš aktivační klíč: {0}\n\nDěkujeme\nTým ETS2MP";
$_lang["no.login"] = "Pro přístup na tuto stránku musíte být přihlášeni.";
$_lang["settings.saved.with.mail"] = "Účet byl uložen. Zkontrolujte si email a aktivujte si znovu váš účet.";
$_lang["new.email.in.use"] = "Tento email je již používán.";
$_lang["email.does.not.match"] = "Poskytnuté emaily nejsou shodné.";
$_lang["invalid.email.format"] = "Zadaný email je neplatný.";
$_lang["new.password.does.not.match"] = "Poskytnutá nová hesla nejsou shodná.";
$_lang["too.short.password"] = "Nové heslo je příliš krátké. Minimum: 5 znaků";
$_lang["old.password.does.not.match"] = "Stará hesla nejsou shodná.";
$_lang["settings.saved"] = "Účet byl uložen.";
$_lang["invalid.old.password"] = "Staré heslo je neplatné, nelze uložit účet.";
$_lang["no.password.change.forced"] = "Pro resetování hesla musíte být odhlášeni.";
$_lang["password.reminder.edit.account"] = "Zapomněli jste heslo? Klikněte <a href=\"index.php?page=resetPassword\">zde</a>.";
$_lang["contact"] = "Kontakt";
$_lang["your.mail"] = "Váš email";
$_lang["content"] = "Zpráva";
$_lang["send"] = "Odeslat";
$_lang["contact.message.sent"] = "Děkujeme, že jste nás kontaktovali. Prosíme, vyčkejte na odpověď";
$_lang["topic"] = "Předmět";
$_lang["contact.message.too.short"] = "Zpráva je moc krátká. Minimum je 10 znaků.";
$_lang["contact.topic.too.short"] = "Předmět je moc krátký. Minimum je 10 znaků.";
$_lang["invalid.mail.forgot.password"] = "Nepodařilo se nám najít žádný účet s tímto emailem.";
$_lang["steamid.in.use"] = "Nalezli jsme ETS2MP účty připojené k tomuto Steam účtu. Pokud máte jakékoli problémy s registrací, <a href=\"http://ets2mp.com/support/\">založte prosím ticket na podpoře</a>.";
$_lang["mail.does.not.match"] = "Zadané email adresy se neshodují.";
$_lang["support"] = "Podpora";
$_lang["profile"] = "Profil";
$_lang["group"] = "Skupina";
$_lang["banned"] = "Zabanován";
$_lang["state"] = "Stav";
$_lang["account.is.activated"] = "Účet je aktivován";
$_lang["account.isnt.activated"] = "Účet není aktivován";
$_lang["penalty.history"] = "Historie trestů";
$_lang["no.punishments"] = "Nenalezen žádný trest.";
$_lang["date"] = "Datum";
$_lang["reason"] = "Důvod";
$_lang["type"] = "Typ";
$_lang["penalty.limit"] = "Do delší historie trestů může nahlížet pouze majitel tohoto profilu.";
