<?php
//
// ETS2MP Homepage language file.
// File:				turkish.php
// Language name: 		Turkish
// Translated name: 	Türkçe
//

$_lang["download"] = "İndir";
$_lang["home"] = "Anasayfa";
$_lang["status"] = "Sunucu Durumu";
$_lang["username"] = "Kullanıcı Adı";
$_lang["password"] = "Şifre";
$_lang["login"] = "Giriş";
$_lang["register"] = "Kayıt Ol";
$_lang["download.latest.version"] = "Son Sürümü İndir";
$_lang["current.release"] = "Şu Anki Sürüm:";
$_lang["language"] = "Dil";
$_lang["join"] = "KATIL";
$_lang["mainpage.join"] = "Binlerce fanatik kamyoncunun arasına katılın!";
$_lang["ts3.advertisement"] = "Diğer sürücüler ile sesli etkileşim - TS3 sunucumuza katılmak için tıklayın.";
$_lang["facebook.advertisement"] = "Bizi Facebook'tan takip edin!";
$_lang["registration.blocked"] = "Kayıt engellendi! - Kayıtların kapalı olmasını gerektiren bazı özellikleri üzerinde çalışıyoruz. Yeni sürüm hazır olduğunda kayıtlar tekrar aktif olacak.";
$_lang["invalid.username.password"] = "Geçersiz kullanıcı adı veya şifre.";
$_lang["already.logged"] = "Zaten oturum açtınız.";
$_lang["welcome"] = "Hoşgeldin";
$_lang["logout"] = "Çıkış";
$_lang["bans"] = "Ban";
$_lang["version"] = "Sürüm";
$_lang["update.time"] = "Güncelleme zamanı";
$_lang["req.game.version"] = "Gerekli oyun sürümü";
$_lang["requires"] = "Gerektirir";
$_lang["or.newer"] = "veya daha yeni";
$_lang["game.client"] = "Oyun İstemcisi";
$_lang["download.no.permissions"] = "Modu indirmeniz için oturum açmanız gerekir.";
$_lang["why.create.account"] = "Neden bir hesap oluşturmalıyım?<br />Bu hesap tüm hizmetlerde oturum açma için kullanılacak (forum, oyun, ekonomi ve diğerleri). Ekonomi ve kişisel sürücü istatistiklerini gelecekte kullanmayı planlıyoruz. Profilinizi değiştirmek mümkün olacak.";
$_lang["website.title"] = "ETS2MP - Sanal Kamyon Dünyası - SCS Software tarafından yapılan Euro Truck Simulator 2 oyunu için çok oyunculu mod";
$_lang["cookies.warning"] = "Bu site <a href=\"http://tr.wikipedia.org/wiki/%C3%87erez_(internet)\">çerezleri</a> kullanmaktadır. Bu siteyi görüntülemeye devam ederek, çerez kullanımını kabul etmiş sayılırsınız.";
$_lang["forum"] = "Forum";
$_lang["cannot.create.account.when.logged"] = "Oturum açıkken yeni bir hesap oluşturamazsınız.";
$_lang["successfully.registered"] = "Başarıyla kayıtlı oldunuz. Lütfen hesabınızı etkinleştirmek için e-postanızı kontrol edin.";
$_lang["error.unknown"] = "Bilinmeyen hata";
$_lang["credentials.taken"] = "Kullanıcı adı, e-posta veya steamid zaten kullanımda.";
$_lang["error.no.steam.data"] = "ETS2MP hesabı oluşturmak için steam kütüphanenizde ETS2 olması gerekir. Eğer varsa, profilinizin herkese açık olup olmadığını kontrol edin.";
$_lang["register.steam.info"] = "Kayıt için steam hesabınıza giriş yapmanız gerekmektedir. Steam kimlik doğrulama sitesine gitmek için aşağıdaki butona basın.";
$_lang["rules.info"] = "Kayıt ol butonuna tıkladığınızda, topluluk kurallarımızı kabul etmiş sayılırsınız. Kuralları kontrol etmek için buraya tıklayın.";
$_lang["mail"] = "E-posta";
$_lang["repeat.mail"] = "E-postayı onayla";
$_lang["new.password"] = "Yeni şifre";
$_lang["repeat.new.password"] = "Yeni şifreyi onayla";
$_lang["new.password.summary"] = "Eğer bu alanları boş bırakırsanız şifre değişmez.";
$_lang["old.password"] = "Eski şifre";
$_lang["repeat.old.password"] = "Eski şifreyi onayla";
$_lang["save.account.data"] = "Hesap Verilerini Kaydet";
$_lang["edit.account"] = "Hesabı Düzenle";
$_lang["forgot.password"] = "Şifrenizi mi unuttunuz? <a href=\"index.php?page=resetPassword\">Buraya</a> tıklayın.";
$_lang["forgot.password.summary"] = "Şifrenizi mi unuttunuz? E-posta adresinizi yazın ve \"Şifre hatırlatma\" butonuna tıklayın.";
$_lang["reminder.button"] = "Şifreyi Sıfırla";
$_lang["reset.password"] = "Şifre Sıfırlama";
$_lang["password.reminder.mail.title"] = "Şifre Sıfırlama İsteği.";
$_lang["password.reminder.content"] = "Merhaba.\n\nBirisi {0} ip adresi ile ETS2MP hesabın için şifre sıfırlama isteği gönderdi.\n\nŞifrenizi sıfırlamak için bu bağlantıya tıklayın: {1}.\nYada bu e-postayı görmezden gelin.\n\nSelamlar\nETS2MP Ekibi";
$_lang["new.password.mail.title"] = "Yeni Şifreniz.";
$_lang["new.password.mail.content"] = "Merhaba.\n\nYeni şifreniz: {0}\n\nHemen giriş yaptıktan sonra değiştirmeyi unutmayın.\n\nSelamlar\nETS2MP Ekibi";
$_lang["account.activated"] = "Hesabınız başarıyla etkinleştirildi.";
$_lang["unable.to.activate"] = "Hesabınız etkinleştirilemiyor, geçersiz anahtar ya da hesap zaten etkinleştirildi.";
$_lang["not.activated"] = "Hesabınız henüz aktif değildir. Etkinleştirme anahtarı yeniden göndermek için <a href=\"index.php?action=resendActivation\">buraya</a> tıklayın.";
$_lang["force.password.change"] = "Lütfen şifrenizi hemen değiştirin. Değiştirmek için <a href=\"index.php?page=editAccount\">buraya</a> tıklayın.";
$_lang["forgot.password.link.sent"] = "E-postanızı kontrol edin. Size şifre sıfırlama bağlantısı göndereceğiz.";
$_lang["forgot.password.sent"] = "E-postanızı kontrol edin. Size yeni bir şifre göndereceğiz.";
$_lang["forgot.password.invalid.key"] = "Geçersiz parola sıfırlama anahtarı.";
$_lang["activation.key.resent"] = "Yeni aktivasyon anahtarı e-posta adresinize gönderildi.";
$_lang["activation.mail.title"] = "ETS2MP Hesap Aktivasyonu.";
$_lang["activation.mail.content"] = "Merhaba.\n\nAktivasyon anahtarınız: {0}\n\nSelamlar\nETS2MP Ekibi";
$_lang["no.login"] = "Bu web sitesine erişmek için oturum açmış olmanız gerekmektedir.";
$_lang["settings.saved.with.mail"] = "Hesap verileri kaydedildi. Yeni e-posta adresinizi kontrol edin ve hesabınızı yeniden etkinleştirin.";
$_lang["new.email.in.use"] = "Bu e-posta zaten kullanılıyor.";
$_lang["email.does.not.match"] = "E-posta adresleri eşleşmiyor.";
$_lang["invalid.email.format"] = "Belirtilen e-posta adresi geçersiz.";
$_lang["new.password.does.not.match"] = "Yeni şifreniz eşleşmiyor.";
$_lang["too.short.password"] = "Yeni şifre çok kısa. Şifreniz en az 5 karakterden oluşmalıdır.";
$_lang["old.password.does.not.match"] = "Eski şifreniz eşleşmiyor.";
$_lang["settings.saved"] = "Hesap kaydedildi.";
$_lang["invalid.old.password"] = "Eski şifre geçersiz, hesap kaydedilemiyor.";
$_lang["no.password.change.forced"] = "Şifrenizi sıfırlamak için oturum açmanız gerekir.";
$_lang["password.reminder.edit.account"] = "Şifreni hatırlamıyor musun? <a href=\"index.php?page=resetPassword\">Buraya</a> tıklayın.";
$_lang["contact"] = "İletişim";
$_lang["your.mail"] = "E-posta";
$_lang["content"] = "Mesaj";
$_lang["send"] = "Gönder";
$_lang["contact.message.sent"] = "Bize ulaştığınız için teşekkür ederiz. Cevap için lütfen bekleyin.";
$_lang["topic"] = "Konu";
$_lang["contact.message.too.short"] = "Mesajınız çok kısa. Mesajınız en az 10 karakter olmalıdır.";
$_lang["contact.topic.too.short"] = "Konu çok kısa. Konu başlığı en az 10 karakter olmalıdır.";
$_lang["invalid.mail.forgot.password"] = "Bu mail ile bağlantılı herhangi bir hesap bulunamadı.";
$_lang["steamid.in.use"] = "Bu steam hesabına bağlı ETS2MP hesapları bulduk. Kayıt ile herhangi bir sorun varsa lütfen <a href=\"http://ets2mp.com/index.php?page=contact\">bize ulaşın</a>.";
$_lang["mail.does.not.match"] = "E-posta adresi eşleşmiyor.";
$_lang["support"] = "Destek";
$_lang["profile"] = "Profil";
$_lang["group"] = "Grup";
$_lang["banned"] = "Yasaklı";
$_lang["state"] = "Durum";
$_lang["account.is.activated"] = "Hesap aktif";
$_lang["account.isnt.activated"] = "Hesap aktif değil";
$_lang["penalty.history"] = "Ceza geçmişi";
$_lang["no.punishments"] = "Gösterilecek ceza bulunamadı.";
$_lang["date"] = "Tarih";
$_lang["reason"] = "Sebep";
$_lang["type"] = "Tür";
$_lang["penalty.limit"] = "Sadece bu profilin sahibi cezaların uzun geçmişini görebilir.";
